version: '3'
services:
  eva-ics:
    container_name: eva_basic_1
    hostname: eva_1
    environment:
      - auto_install=1
      - mqtt=10.27.5.200
      - link=1
      - product=all
      - layout=enterprise
      - MASTERKEY=demo123
    image: altertech/eva-ics
    volumes:
        - runtime:/runtime
        - ui:/ui
        - backup:/backup
    networks:
      ic:
        ipv4_address: 10.27.5.10

  mqtt:
    container_name: eva_basic_mqtt
    image: eclipse-mosquitto
    networks:
      ic:
        ipv4_address: 10.27.5.200

networks:
  ic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.27.5.0/24

volumes:
  ui:
  runtime:
  backup:
