#!/bin/sh

VERSION=`grep "^__version__ = " sbin/ucserv.py|cut -d= -f2|awk '{ print $1 }'| tr -d '"'`
BUILD=`grep "^product_build = " sbin/ucserv.py|cut -d= -f2|awk '{ print $1 }'`

#scp -P 222 update.sh root@d1.altertech.net:/www/download/eva-ics/${VERSION}/nightly/update-${BUILD}.sh
#scp -P 222 update.sh root@d1.altertech.net:/www/download/test.eva-ics/${VERSION}/nightly/update-${BUILD}.sh
#scp -P 222 UPDATE.rst root@d1.altertech.net:/www/download/eva-ics/${VERSION}/nightly/
#scp -P 222 UPDATE.rst root@d1.altertech.net:/www/download/test.eva-ics/${VERSION}/nightly/

gsutil cp -a public-read update.sh gs://pub.bma.ai/eva3/${VERSION}/nightly/update-${BUILD}.sh
gsutil -h "Content-Type:text/x-rst" cp -a public-read UPDATE.rst gs://pub.bma.ai/eva3/${VERSION}/nightly/UPDATE.rst

