#!/bin/sh

D=`realpath $0`
EVA_DIR=`dirname ${D}`/..
EVA_DIR=`realpath ${EVA_DIR}`

PYTHON=${EVA_DIR}/python3/bin/python3

P=`basename $0`

if [ "$P" = "venvl" ]; then
  echo "Don't start this script directly"
  exit 1
fi

PROGRAM=${EVA_DIR}/cli/${P}.py

${PYTHON} ${PROGRAM} $*
