#!/usr/bin/env bash

EVA_DIR=$(realpath "$(dirname "$(realpath "$0")")/..")
PYTHON="${EVA_DIR}"/venv/bin/python

P=$(basename "$0")

if [ "$P" = "venvl" ]; then
  echo "Don't start this script directly"
  exit 1
fi

PROGRAM="${EVA_DIR}"/cli/"${P}".py

"${PYTHON}" "${PROGRAM}" "$@"
