#!/bin/bash

TIMEOUT=3

PORT=6722

IP=$1
RELAY=$2
MODE=$3

if [ "x${MODE}" = "x" ]; then
    echo "Usage: SR-201 <IP> [RELAY] [MODE]"
    echo
    echo "IP                    Device IP"
    echo "RELAY                 Relay number"
    echo "MODE                  0 - off, 1 - on"
    echo
    echo "If RELAY/MODE are not provided, the script displays"
    echo "the current socket states"
    echo
    exit 99
fi

if [ "x${MODE}" != "x" ]; then
    [ "x${MODE}" == "x0" ] && M=2 || M=1
    RESULT=`echo -n ${M}${RELAY} | nc -w ${TIMEOUT} ${IP} ${PORT} | cut -c${RELAY}`
    [ "x${RESULT}" == "x${M}" ] && exit 0 || exit 1
    else
    echo -n 00 | nc -w ${TIMEOUT} ${IP} ${PORT} | sed 's/\(.\)/\1\n/g'
fi
