#!/usr/bin/env bash

DEFAULT_TIMEOUT=15

# author     :  Altertech Group, http://www.altertech.com/
# copyright  :  Copyright (C) 2018 Altertech Group
# license    :  Apache License 2.0

shopt -s extglob

D=`realpath $0`
cd `dirname ${D}`/..

_CONFIG=()
_SECTIONS=""
_PROP=""

_EX=1

PRODUCT=
FUNCTION=
#SYSAPI=
VERBOSE=0

function echoV() {
    [ ${VERBOSE} -gt 0 ] && echo $*
}

function parseIniFile() {
    local LINE=""
    local SECTION=""
    local KEY=""
    local VALUE=""

    local IFS=""

    while read LINE 
    do
        LINE=${LINE%%[;#]*}
        LINE=${LINE%%*( )}

        if [[ -n $KEY && $LINE =~ ^[[:space:]]+(.+) ]]
        then
            VALUE+=" ${BASH_REMATCH[1]}"
        else
            if [[ -n $KEY ]]
            then
                _CONFIG=(${_CONFIG[@]} "${SECTION}.${KEY}" "${VALUE}")
                KEY=""
                VALUE=""
            fi

            if [[ $LINE =~ ^\[([[:alnum:]]+)\] ]]
            then
                SECTION=${BASH_REMATCH[1]}
                _SECTIONS="${_SECTIONS} ${SECTION}"
                KEY=""
            elif [[ $LINE =~ ^([^[:space:]]+)[[:space:]]*=[[:space:]]*(.+) ]]
            then 
                KEY=${BASH_REMATCH[1]}
                VALUE="${BASH_REMATCH[2]}"
            fi
        fi
    done

    if [[ -n $KEY ]]
    then
        _CONFIG=(${_CONFIG[@]} "${SECTION}.${KEY}" "${VALUE}")
    fi
}

function getProperty() {
	_PROP=""
    local -i i
    local KEY=$1
    for ((i=0; i<${#_CONFIG[@]}; i+=2))
    do
        if [[ ${_CONFIG[$i]} =~ ^\.?${KEY} ]]
        then
            _PROP=${_CONFIG[((i+1))]}
            return 0
        fi
    done
    return 1
}

function showHelp() {
cat <<EOF
EVA API direct call CLI

Usage: eva-tinyapi <-T timeout> <-C type> <-F function> [params]

    -T      API call timeout (default: ${DEFAULT_TIMEOUT})
    -C      uc, lm or sfa
    -F      API function
    -v      verbose mode
    params  API function params (e.g. i=test full=1), space separated

    -V      print EVA version and exit
    -B      print EVA build and exit

Exit code = curl exit code

WARNING: eva-tinyapi has been tested with basic API functions only and not
recommended to use in a production unless in EVA internal scripts.
EOF
}

TIMEOUT=${DEFAULT_TIMEOUT}
DATA=


while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -C)
            PRODUCT="$2"
            shift
            shift
        ;;
        -T) TIMEOUT="$2"
            shift
            shift
        ;;
        -F) FUNCTION="$2"
            shift
            shift
        ;;
        -v) VERBOSE=1
            shift
        ;;
        -vv) VERBOSE=2
            shift
        ;;
        -h) showHelp
            exit 0
        ;;
        -V) grep ^__version__ ./sbin/ucserv.py |cut -d\" -f2
            exit 0
        ;;
        -B) grep ^product_build ./sbin/ucserv.py |cut -d= -f2|sed 's/ //g'
            exit 0
        ;;
        *)
            echo $1 | grep '=' > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                [ "x$DATA" = "x" ] || DATA="${DATA}, "
                D=`echo $1 | sed "s/\(.*\)=\(.*\)/\"\1\" : \"\2\"/g"`
                shift;
                DATA="${DATA} ${D}"
            else
                echo "Unknown option: ${key}"
                showHelp
                exit -1
            fi
        ;;
    esac
done

if [ "x$PRODUCT" = "x" ] || [ "x$FUNCTION" = "x" ]; then
        echo "No product or function specified"
        echo
        showHelp
        exit -1
fi

cat ./etc/${PRODUCT}.ini > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Can't open ${PRODUCT}.ini"
    exit 9
fi

cat ./etc/${PRODUCT}_apikeys.ini > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Can't open ${PRODUCT}_apikeys.ini"
    exit 9
fi

parseIniFile < ./etc/${PRODUCT}.ini

getProperty webapi.listen
U="http://"

if [ "x$_PROP" = "x" ]; then
    getProperty webapi.ssl_listen
    if [ "x$_PROP" = "x" ]; then
        echo "Can't find API host/port in ${PRODUCT}.ini"
        exit 9
    fi
    U="https://"
fi

U="$U`echo $_PROP | sed 's/0.0.0.0/127.0.0.1/'`"

#if [ "x$SYSAPI" = "x" ]; then
    #U="$U/${PRODUCT}-api/"
    #else
    #U="$U/sys-api/"
#fi

U="${U}/jrpc"

parseIniFile < ./etc/${PRODUCT}_apikeys.ini

getProperty masterkey.key

if [ "x$_PROP" = "x" ]; then
    echo "Can't find masterkey in ${PRODUCT}_apikeys.ini"
    exit 9
fi

[ "x$DATA" = "x" ] || DATA="${DATA}, "

DATA="$DATA \"k\" : \"$_PROP\""

ID=1
DATA="{ \"jsonrpc\": \"2.0\", \"method\": \"${FUNCTION}\", \"params\": { ${DATA} }, \"id\": \"${ID}\"}"

echoV "API call to $U"
echoV "Timeout: ${TIMEOUT}"

if [ ${VERBOSE} == "2" ]; then
    VERB="-v"
else
    VERB=
fi

if [ $VERB ]; then
  echo $DATA | curl --header "Content-Type: application/json" --data @- -X POST -m ${TIMEOUT} -s ${VERB} $U
else
  RESULT=`echo $DATA | curl --header "Content-Type: application/json" --data @- -X POST -m ${TIMEOUT} -s ${VERB} $U`
fi
_EX=$?
echoV
echoV "Curl exit code: $_EX"
if [ ${VERB} ]; then
  exit $_EX
fi
if [ $_EX -ne 0 ]; then
  echo "Server error"
  exit 7
fi

R=`echo $RESULT|jq .result 2>&1`

if [ $? -ne 0 ] || [ "x$R" == "xnull" ]; then
  ERROR_CODE=`echo $RESULT|jq -Mr .error.code 2>&1`
  if [ $? -ne 0 ]; then
    exit 9
  fi
  ERROR_MESSAGE=`echo $RESULT|jq -Mr .error.message 2>&1`
  if [ $? -ne 0 ] || [ "x$ERROR_CODE" == "xnull" ]; then
    exit 9
  fi
  echo ${ERROR_MESSAGE}
  exit ${ERROR_CODE}
fi

echo $R

exit 0
