#!/bin/bash

PYTHON=python3

D=`realpath $0`
cd `dirname ${D}`/..

WAIT_TO_KILL=40 # sec * 2 before kill -KILL

export EVA_DIR=`pwd`

PIDFILE=${EVA_DIR}/var/lm.pid
LM=${EVA_DIR}/sbin/lmserv.py
LM_ARGS=
SAFE_RUN_PIDFILE=${EVA_DIR}/var/lm_safe.pid
WATCHDOG_PIDFILE=${EVA_DIR}/var/lm_watchdog.pid
SAFE_RUN=${EVA_DIR}/sbin/safe-run.sh
WATCHDOG=${EVA_DIR}/sbin/watchdog.sh

source ./etc/eva_servers

function exec_cmd {
    if [ "x${LM_USER}" == "x" ]; then
        $*
    else
        su ${LM_USER} -c "$*"
    fi
}

if [ ${LM_SUPERVISORD} ]; then
    case $1 in
        start)
            supervisorctl start ${LM_SUPERVISORD}
            supervisorctl start watchdog-${LM_SUPERVISORD}
            exit $?
        ;;
        stop)
            supervisorctl stop watchdog-${LM_SUPERVISORD}
            supervisorctl stop ${LM_SUPERVISORD}
            exit $?
        ;;
        status)
            supervisorctl status ${LM_SUPERVISORD}
            exit $?
        ;;
        restart)
            supervisorctl restart ${LM_SUPERVISORD}
            supervisorctl restart watchdog-${LM_SUPERVISORD}
            exit $?
        ;;
    esac
fi

case $1 in
start)
    echo 'Starting LM server'
    ps xa|grep -v grep|grep ${LM} > /dev/null 2>&1
    if [ $? == 0 ]; then
        echo "already started"
        exit 2
    fi
    exec_cmd ${SAFE_RUN} ${SAFE_RUN_PIDFILE} ${PYTHON} ${LM} ${LM_ARGS} > /dev/null &
    ${WATCHDOG} lm ${LM} > /dev/null &
    ;;
launch)
    [ "x$2" = "xdebug" ] && DEBUG="EVA_CORE_DEBUG=1" || DEBUG=
    env EVA_CORE_ENABLE_CC=1 EVA_CORE_LOG_STDOUT=1 ${DEBUG} ${PYTHON} ${LM} ${LM_ARGS}
    ;;
stop)
    ps xa|grep -v grep|grep ${LM} > /dev/null 2>&1
    [ $? == 0 ] || exit 1
    echo -n 'Stopping LM server '
    PID_SAFE_RUN=
    PID_LM=
    PID_WATCHDOG=
    [ -f ${SAFE_RUN_PIDFILE} ] && PID_SAFE_RUN=`cat ${SAFE_RUN_PIDFILE}`
    [ -f ${WATCHDOG_PIDFILE} ] && PID_WATCHDOG=`cat ${WATCHDOG_PIDFILE}`
    [ -f ${PIDFILE} ] && PID_LM=`cat ${PIDFILE}`
    if [ "x${PID_WATCHDOG}" != "x" ]; then
        kill ${PID_WATCHDOG} > /dev/null 2>&1
        rm -f ${WATCHDOG_PIDFILE}
    fi
    if [ "x${PID_SAFE_RUN}" != "x" ]; then
        kill ${PID_SAFE_RUN} > /dev/null 2>&1
        rm -f ${SAFE_RUN_PIDFILE}
    fi
    if [ "x${PID_LM}" != "x" ]; then
        kill ${PID_LM} > /dev/null 2>&1
        I=0
        while kill -0 ${PID_LM} > /dev/null 2>&1; do
            echo -n '.'
            sleep 0.5
            I=`expr ${I} + 1`
            if [ ${I} -ge ${WAIT_TO_KILL} ]; then
                echo -n  'killing '
                kill -KILL ${PID_LM}
                break
            fi
        done
        rm -f ${PIDFILE}
    fi
    ps xa|grep -v grep|grep ${LM}|awk '{ print $1 }'|xargs kill > /dev/null 2>&1
    if [ $? == 0 ]; then
        sleep 10
        ps xa|grep -v grep|grep ${LM}|awk '{ print $1 }'|xargs kill -9 > /dev/null 2>&1
    fi
    echo ' stopped'
    ;;
restart)
    ./sbin/lm-control stop $2
    ./sbin/lm-control start $2
    ;;
logrotate)
    [ -f ${PIDFILE} ] && kill -HUP `cat ${PIDFILE}`
    ;;
status)
    ps xa|grep -v grep|grep ${LM} > /dev/null 2>&1
    if [ $? == 0 ]; then
        echo "running"
    else
        echo "stopped"
    fi
    ;;
version)
    exec_cmd ${PYTHON} ${LM} -V
    ;;
*)
    echo "Usage: lm-control start|stop|restart|logrotate|version"
esac
