#!/bin/sh

PYTHON=python3

D=`realpath $0`
cd `dirname ${D}`/..

WAIT_TO_KILL=40 # sec * 2 before kill -KILL

export EVA_DIR=`pwd`

PIDFILE=${EVA_DIR}/var/uc.pid
UC=${EVA_DIR}/sbin/ucserv.py
UC_ARGS=
SAFE_RUN_PIDFILE=${EVA_DIR}/var/uc_safe.pid
SAFE_RUN=${EVA_DIR}/sbin/safe-run.sh

source ./etc/eva_servers

function exec_cmd {
    if [ "x${UC_USER}" == "x" ]; then
        $*
    else
        su ${UC_USER} -c "$*"
    fi
}

case $1 in
start)
    echo 'Starting UC server'
    exec_cmd ${SAFE_RUN} ${SAFE_RUN_PIDFILE} ${PYTHON} ${UC} ${UC_ARGS} > /dev/null &
    ;;
launch)
    exec_cmd ${PYTHON} ${UC} ${UC_ARGS}
    ;;
stop)
    [ -f ${PIDFILE} ] || exit 1
    echo -n 'Stopping UC server '
    PID_SAFE_RUN=
    PID_UC=
    [ -f ${SAFE_RUN_PIDFILE} ] && PID_SAFE_RUN=`cat ${SAFE_RUN_PIDFILE}`
    [ -f ${PIDFILE} ] && PID_UC=`cat ${PIDFILE}`
    if [ "x${PID_SAFE_RUN}" != "x" ]; then
        kill ${PID_SAFE_RUN} > /dev/null 2>&1
        rm -f ${SAFE_RUN_PIDFILE}
    fi
    if [ "x${PID_UC}" != "x" ]; then
        kill ${PID_UC} > /dev/null 2>&1
        I=0
        while kill -0 ${PID_UC} > /dev/null 2>&1; do
            echo -n '.'
            sleep 0.5
            I=`expr ${I} + 1`
            if [ ${I} -ge ${WAIT_TO_KILL} ]; then
                echo -n  'killing '
                kill -KILL ${PID_UC}
                break
            fi
        done
        rm -f ${PIDFILE}
    fi
    echo ' stopped'
    ;;
restart)
    ./sbin/uc-control stop $2
    ./sbin/uc-control start $2
    ;;
logrotate)
    [ -f ${PIDFILE} ] && kill -HUP `cat ${PIDFILE}`
    ;;
version)
    exec_cmd ${PYTHON} ${UC} -V
    ;;
*)
    echo "Usage: uc-control start|stop|restart|logrotate|version"
esac
