#!/bin/bash

PYTHON=python3

D=`realpath $0`
cd `dirname ${D}`/..

WAIT_TO_KILL=40 # sec * 2 before kill -KILL

export EVA_DIR=`pwd`

PIDFILE=${EVA_DIR}/var/uc.pid
UC=${EVA_DIR}/sbin/ucserv.py
UC_ARGS=
SAFE_RUN_PIDFILE=${EVA_DIR}/var/uc_safe.pid
WATCHDOG_PIDFILE=${EVA_DIR}/var/uc_watchdog.pid
SAFE_RUN=${EVA_DIR}/sbin/safe-run.sh
WATCHDOG=${EVA_DIR}/sbin/watchdog.sh

source ./etc/eva_servers

if [ ${UC_SUPERVISORD} ]; then
    case $1 in
        start)
            supervisorctl start ${UC_SUPERVISORD}
            supervisorctl start watchdog-${UC_SUPERVISORD}
            exit $?
        ;;
        stop)
            supervisorctl stop watchdog-${UC_SUPERVISORD}
            supervisorctl stop ${UC_SUPERVISORD}
            exit $?
        ;;
        status)
            supervisorctl status ${UC_SUPERVISORD}
            exit $?
        ;;
        restart)
            supervisorctl restart watchdog-${UC_SUPERVISORD}
            supervisorctl restart ${UC_SUPERVISORD}
            exit $?
        ;;
    esac
fi

function exec_cmd {
    if [ "x${UC_USER}" == "x" ]; then
        $*
    else
        su ${UC_USER} -c "$*"
    fi
}

case $1 in
start)
    echo 'Starting UC server'
    ps xa|grep -v grep|grep ${UC} > /dev/null 2>&1
    if [ $? == 0 ]; then
        echo "already started"
        exit 2
    fi
    exec_cmd ${SAFE_RUN} ${SAFE_RUN_PIDFILE} ${PYTHON} ${UC} ${UC_ARGS} > /dev/null &
    ${WATCHDOG} uc ${UC} > /dev/null &
    ;;
launch)
    [ "x$2" = "xdebug" ] && DEBUG="EVA_CORE_DEBUG=1" || DEBUG=
    env EVA_CORE_ENABLE_CC=1 EVA_CORE_LOG_STDOUT=1 ${DEBUG} ${PYTHON} ${UC} ${UC_ARGS}
    ;;
stop)
    ps xa|grep -v grep|grep ${UC} > /dev/null 2>&1
    [ $? == 0 ] || exit 1
    echo -n 'Stopping UC server '
    PID_SAFE_RUN=
    PID_UC=
    PID_WATCHDOG=
    [ -f ${SAFE_RUN_PIDFILE} ] && PID_SAFE_RUN=`cat ${SAFE_RUN_PIDFILE}`
    [ -f ${WATCHDOG_PIDFILE} ] && PID_WATCHDOG=`cat ${WATCHDOG_PIDFILE}`
    [ -f ${PIDFILE} ] && PID_UC=`cat ${PIDFILE}`
    if [ "x${PID_WATCHDOG}" != "x" ]; then
        kill ${PID_WATCHDOG} > /dev/null 2>&1
        rm -f ${WATCHDOG_PIDFILE}
    fi
    if [ "x${PID_SAFE_RUN}" != "x" ]; then
        kill ${PID_SAFE_RUN} > /dev/null 2>&1
        rm -f ${SAFE_RUN_PIDFILE}
    fi
    if [ "x${PID_UC}" != "x" ]; then
        kill ${PID_UC} > /dev/null 2>&1
        I=0
        while kill -0 ${PID_UC} > /dev/null 2>&1; do
            echo -n '.'
            sleep 0.5
            I=`expr ${I} + 1`
            if [ ${I} -ge ${WAIT_TO_KILL} ]; then
                echo -n  'killing '
                kill -KILL ${PID_UC}
                break
            fi
        done
        rm -f ${PIDFILE}
    fi
    ps xa|grep -v grep|grep ${UC}|awk '{ print $1 }'|xargs kill > /dev/null 2>&1
    if [ $? == 0 ]; then
        sleep 10
        ps xa|grep -v grep|grep ${UC}|awk '{ print $1 }'|xargs kill -9 > /dev/null 2>&1
    fi
    echo ' stopped'
    ;;
restart)
    ./sbin/uc-control stop $2
    ./sbin/uc-control start $2
    ;;
logrotate)
    [ -f ${PIDFILE} ] && kill -HUP `cat ${PIDFILE}`
    ;;
status)
    ps xa|grep -v grep|grep ${UC} > /dev/null 2>&1
    if [ $? == 0 ]; then
        echo " running "
    else
        echo " stopped "
    fi
    ;;
version)
    exec_cmd ${PYTHON} ${UC} -V
    ;;
*)
    echo "Usage: uc-control start|stop|restart|logrotate|version"
esac
