#!/bin/bash -x

[ -f /.installed  ] && exit 0
while [ 1 ]; do
  cd /opt
  # download EVA ICS
  if [ ${download} ]; then
      rm -f eva-dist.tgz
      curl ${download} -o eva-dist.tgz
      if [ $? -ne 0 ]; then
          echo "Unable to connect to EVA ICS repository. Will try again in 5 seconds..."
          sleep 5
          continue
      fi
  fi
  find . -maxdepth 1 -type d -name "eva*" -exec rm -rf {} \;
  tar xzf eva-dist.tgz
  if [ $? -ne 0 ]; then
      echo "Unable to get EVA ICS distribution. Will try again in 5 seconds..."
      sleep 5
      continue
  fi
  find . -maxdepth 1 -type d -name "eva-*" -exec mv -f {} eva \;
  # connect runtime volume if exists
  [ -d /runtime ] && ln -sf /runtime /opt/eva/runtime
  # turn on debug mode
  bash_debug_opts=
  if [ ${debug} ] || [ ${development_mode} ]; then
      [ ${development_mode} ] && devmode='\ndevelopment = yes' || devmode=
      sed -i "s/^debug =.*/debug = yes${devmode}/g" eva/etc/*.ini-dist
      bash_debug_opts=-x
  fi
  # connect ui volume if exists
  if [ -d /ui ]; then
      if [ -z "$(ls -A /ui)" ]; then
          # empty ui, putting default
          mv /opt/eva/ui/* /ui/
      fi
      rm -rf /opt/eva/ui
      ln -sf /ui /opt/eva/ui
  fi
  # connect backup volume if exists
  [ -d /backup ] && ln -sf /backup /opt/eva/backup
  # setup EVA ICS
  MQTT_OPTS=
  LINK_OPTS=
  CM_OPTS=
  DEPLOY_OPTS=
  [ "x${link}" = "x1" ] && LINK_OPTS="--link"
  [ "x${cloud_manager}" = "x1" ] && CM_OPTS="--cloud-manager"
  [ "x${deploy}" != "x" ] && DEPLOY_OPTS="--deploy"
  [ ${mqtt} ] && MQTT_OPTS="--mqtt"
  [ ${product} ] || product=all
  cd /opt/eva
  rm -rf runtime/*_notify.d runtime/*_remote_*.d
  bash ${bash_debug_opts} ./easy-setup --skip-check --auto --supervisor \
    ${AUTO_OPTS} ${MQTT_OPTS} ${mqtt} ${LINK_OPTS} -p ${product} \
    ${CM_OPTS} ${DEPLOY_OPTS} ${deploy}
  result=$?
  if [ ${result} -eq 0 ]; then
      # create install flag
      touch /.installed
      rm -f /etc/supervisor/conf.d/eva-install.conf
      supervisorctl update
      break
  else
      echo "SETUP FAILED. CODE: ${result}"
      exit 5
  fi
done

rm -f $0
exit 0
