#!/usr/bin/env bash

which realpath > /dev/null
if [ $? != 0 ]; then
    echo 'please install realpath'
    exit 1
fi

D=`realpath $0`
cd `dirname ${D}`/..

echo "Installing EVA SFA to `pwd`"

echo "Creating dirs"
mkdir -p ./etc || exit 1
chmod 755 ./etc
mkdir -p ./var || exit 1
mkdir -p ./log || exit 1
mkdir -p ./runtime || exit 1
mkdir -p ./runtime/data || exit 1
mkdir -p ./runtime/xc/sfa/cs || exit 1
mkdir -p ./runtime/db || exit 1
touch runtime/db/sfa.db || exit 1
mkdir -p ./runtime/xc/cmd || exit 1
mkdir -p pvt
chmod 700 pvt

(cd ./lib/eva && ln -sf ../../plugins) || exit 1
(cd xc && ln -sf ../runtime/xc/sfa) || exit 1
(cd xc && ln -sf ../runtime/xc/cmd) || exit 1

echo "Performing initial config"

echo "Finished"

exit 0
