#!/usr/bin/env bash

which realpath > /dev/null
if [ $? != 0 ]; then
    echo 'please install realpath'
    exit 1
fi

D=`realpath $0`
cd `dirname ${D}`/..

echo "Installing EVA LM PLC to `pwd`"

echo "Creating dirs"
mkdir -p ./etc || exit 1
chmod 755 ./etc
mkdir -p ./var || exit 1
mkdir -p ./log || exit 1
mkdir -p ./runtime || exit 1
mkdir -p ./runtime/lm_notify.d || exit 1
chmod 700 ./runtime/lm_notify.d || exit 1
mkdir -p ./runtime/lm_dmatrix_rule.d || exit 1
chmod 700 ./runtime/lm_dmatrix_rule.d || exit 1
mkdir -p ./runtime/lm_lmacro.d || exit 1
mkdir -p ./runtime/lm_lcycle.d || exit 1
mkdir -p ./runtime/lm_lvar.d || exit 1
mkdir -p ./runtime/lm_remote_uc.d || exit 1
chmod 700 ./runtime/lm_remote_uc.d || exit 1
mkdir -p ./runtime/db || exit 1
touch runtime/db/lm.db || exit 1
mkdir -p ./runtime/xc/lm || exit 1
mkdir -p ./xc/cmd || exit 1
mkdir -p ./xc/extensions || exit 1

(cd xc && ln -sf ../runtime/xc/lm) || exit 1
(cd lib/eva/lm && ln -sf ../../../xc/extensions) || exit 1
(cd xc/extensions && ln -sf ../../lib/eva/lm/generic/generic_ext.py generic.py) || exit 1

echo "Performing initial config"

[ -f ./runtime/lm_cvars.json ] || echo "{}" > ./runtime/lm_cvars.json
[ -f ./runtime/lm_extensions.json ] || echo "{}" > ./runtime/lm_extensions.json

echo "Finished"

exit 0
