#!/bin/bash

which realpath > /dev/null
if [ $? != 0 ]; then
    echo 'please install realpath'
    exit 1
fi

D=`realpath $0`
cd `dirname ${D}`/..

which pip3 > /dev/null
if [ $? != 0 ]; then
    echo 'please install pip3'
    exit 1
fi

echo "Installing EVA UC to `pwd`"

echo "Creating dirs"
mkdir -p ./etc || exit 1
chmod 755 ./etc
mkdir -p ./var || exit 1
mkdir -p ./log || exit 1
mkdir -p ./runtime || exit 1
mkdir -p ./runtime/virtual || exit 1
mkdir -p ./runtime/uc_notify.d || exit 1
chmod 700 ./runtime/uc_notify.d || exit 1
mkdir -p ./runtime/uc_unit.d || exit 1
mkdir -p ./runtime/uc_sensor.d || exit 1
mkdir -p ./runtime/uc_mu.d || exit 1
mkdir -p ./runtime/db || exit 1
mkdir -p ./runtime/tpl || exit 1
touch runtime/db/uc.db || exit 1
mkdir -p ./runtime/xc || exit 1
mkdir -p ./runtime/xc/uc || exit 1
mkdir -p ./xc/cmd || exit 1
mkdir -p ./xc/drivers/phi || exit 1
mkdir -p ./xc/drivers/lpi || exit 1

(cd xc && ln -sf ../runtime/xc/uc) || exit 1
(cd lib/eva/uc && ln -sf ../../../xc/drivers) || exit 1
(cd xc/drivers/phi && ln -sf ../../../lib/eva/uc/generic/generic_phi.py) || exit 1
(cd xc/drivers/lpi && ln -sf ../../../lib/eva/uc/generic/generic_lpi.py) || exit 1

echo "Performing initial config"

[ -f ./runtime/uc_cvars.json ] || echo "{}" > ./runtime/uc_cvars.json
[ -f ./runtime/uc_drivers.json ] || echo "{}" > ./runtime/uc_drivers.json
[ -f ./runtime/uc_modbus.json ] || echo "[]" > ./runtime/uc_modbus.json

echo "Finished"

exit 0
