#!/usr/bin/env bash

which realpath > /dev/null
if [ $? != 0 ]; then
    echo 'please install realpath'
    exit 1
fi

D=`realpath $0`
cd `dirname ${D}`/..

echo "Installing EVA UC to `pwd`"

echo "Creating dirs"
mkdir -p ./etc || exit 1
chmod 755 ./etc
mkdir -p ./var || exit 1
mkdir -p ./log || exit 1
mkdir -p ./runtime || exit 1
mkdir -p ./runtime/data || exit 1
mkdir -p ./runtime/db || exit 1
mkdir -p ./runtime/tpl || exit 1
touch runtime/db/uc.db || exit 1
mkdir -p ./runtime/xc || exit 1
mkdir -p ./runtime/xc/uc || exit 1
mkdir -p ./runtime/xc/uc/cs || exit 1
mkdir -p ./runtime/xc/cmd || exit 1
mkdir -p ./runtime/drivers || exit 1
mkdir -p ./runtime/drivers/lpi || exit 1
mkdir -p ./runtime/drivers/phi || exit 1
mkdir -p ./runtime/plugins || exit 1
touch ./runtime/plugins/__init__.py

(cd ./lib/eva && ln -sf ../../runtime/plugins) || exit 1

echo "Performing initial config"

echo "Finished"

exit 0
