#!/usr/bin/env bash

cd "$(realpath "$(dirname "$(realpath "$0")")/..")" || exit 1

ln -sf eva bin/eva-shell

mkdir -p bin sbin tests
ln -sf ../cli/venvl tests/benchmark-uc-crt

BIN="uc-cmd lm-cmd sfa-cmd test-uc-xc test-ext test-phi uc-tpl prepare-sr gen-intl key-deploy key-import"
NBIN="uc-notifier lm-notifier sfa-notifier"
SBIN="check-mqtt check-psrt get-setup-options eva-update-tables apikey-set pypi-mirror"
INSTALL="import-registry-defaults import-registry-schema convert-legacy-configs switch-mqtt-psrt switch-controller-notifier"

for p in ${BIN}; do
  ln -sf ../cli/venvl bin/"${p}"
done

for p in ${NBIN}; do
  ln -sf ../cli/notifymanager.sh bin/"${p}"
done

for p in ${SBIN}; do
  ln -sf ../cli/venvl sbin/"${p}"
done

for p in ${INSTALL}; do
  ln -sf ../cli/venvl install/"${p}"
done
