#!/bin/sh

code=0
[ "x$1" != "x" ] && code=$1

echo "test script start"
echo "param 1: $1 ( > 0 will generate \"failed\" status)"
echo "param 2: $2"
echo "param 3: $3"
echo "delay 3 sec"
sleep 3
echo "script finish"
exit ${code}
